### ISSUE TITLE
building las curve from scratch

### ISSUE THREAD

**Issue by diverdude** [kinverarity1/las-reader#33]
Could you add an example where you start with an empty LAS object and then build a las object in code, and finally save it to the file?

**Comment by kinverarity1** [comment]
Yep. I'll make some changes to the las_reader code to make it easier too.

**Comment by kinverarity1** [comment]
Take a look at [las-reader/docs/Example - build LAS file from scratch.ipynb](https://github.com/kinverarity1/las-reader/blob/master/docs/Example%20-%20build%20LAS%20file%20from%20scratch.ipynb)

**Comment by VelizarVESSELINOV** [comment]
Is the library only LAS reader or it is also writer?

Thanks,
Velizar

**Comment by diverdude** [comment]
hi velizar
The LAS reader can both read and write LAS 1.2 and 2.0 data.
I tried it and we got a few small things fixed, but it seems to do a really
good job.

On Sun, Aug 2, 2015 at 3:42 AM, Velizar VESSELINOV <notifications@github.com
> wrote:

> Is the library only LAS reader or it is also writer?
>
> Thanks,
> Velizar
>
> Sent from my iPhone
>
>
> > On Jul 31, 2015, at 11:35 PM, Kent Inverarity <notifications@github.com>
> wrote:
> >
> > Take a look at las-reader/docs/Example - build LAS file from
> scratch.ipynb
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kinverarity1/las-reader/issues/33#issuecomment-126973001>
> .
>



-- 
Med venlig hilsen
Bjørn Skovlund Dissing

**Comment by VelizarVESSELINOV** [comment]
Maybe the name of the package should be renamed to avoid misinterpretation.
Example: SEG-Y Python read/write library is called Segpy, so why not something like Laspy or LasIO...

**Comment by kinverarity1** [comment]
Probably a good idea. ``laspy`` is the name of a well-established package for reading Lidar data files, which also have a .las extension.

I don't want upper-case letters -- my preference would probably be ``lasio``.

**Comment by kinverarity1** [comment]
I would perhaps like the name, if changed, to have a more obvious connection to the subject matter. How about ``boreholelas``, ``boreholelasfiles``, or ``pyboreholelas``?

**Comment by VelizarVESSELINOV** [comment]
I'm not big fan of very long name and not sure **borehole** is very popular term.

When I look the LAS wikipedia page (https://en.wikipedia.org/wiki/Log_ASCII_Standard) the most used term is **well**:
1. las_well :+1:
2. laswell
3. well_las
4. welllas too much **l** :-1:

Shorter version with **w**
5. wlas :+1: but the auto-completion try to change it all the time to was :-1: 
6. lasw

Longer version with **wellbore** or (**wb** abbreviation). I'm use to use the term wellbore rather than borehole, but it is longer term and also more technical.

So my preferred shorter list:
1. las_io (to keep it closer to the original name, other packages are using also _io suffix like https://pypi.python.org/pypi/htk_io/0.5, https://pypi.python.org/pypi/UFF_IO/0.1.5a1, etc.)
2. lasio (make me think about Roma and holidays :))
3. wlas (for well/wellbore LAS reader/writer)

What do you think?

**Comment by diverdude** [comment]
i agree with Velizar,
borehole feels strange.
wlas is good.
how about
wiolas ?


On Mon, Aug 3, 2015 at 3:58 PM, Velizar VESSELINOV <notifications@github.com
> wrote:

> I'm not big fan of very long name and not sure *borehole* is very popular
> term.
>
> When I look the LAS wikipedia page (
> https://en.wikipedia.org/wiki/Log_ASCII_Standard) the most used term is
> *well*:
> 1. las_well [image: :+1:]
> 2. laswell
> 3. well_las
> 4. welllas too much *l* [image: :-1:]
>
> Shorter version with *w*
> 5. wlas [image: :+1:] but the auto-completion try to change it all the
> time to was [image: :-1:]
> 6. lasw
>
> Longer version with *wellbore* or (*wb* abbreviation). I'm use to use the
> term wellbore rather than borehole, but it is longer term and also more
> technical.
>
> So my preferred shorter list:
> 1. las_io (to keep it closer to the original name, other packages are
> using also _io suffix like https://pypi.python.org/pypi/htk_io/0.5,
> https://pypi.python.org/pypi/UFF_IO/0.1.5a1, etc.)
> 2. lasio (make me think about Roma and holidays :))
> 3. wlas (for well/wellbore LAS reader/writer)
>
> What do you think?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kinverarity1/las-reader/issues/33#issuecomment-127246230>
> .
>



-- 
Med venlig hilsen
Bjørn Skovlund Dissing

**Comment by kinverarity1** [comment]
Let's use ``lasio``.
