### ISSUE TITLE
STRT STOP STEP not updating

### ISSUE THREAD

**Issue by diverdude** [kinverarity1/las-reader#35]
Using your example i am trying to set some header items.
It seems that some of them is writing fine to file while others are not updated when flushed to file.
Specifically STRT, STOP and STEP seem to keep the default values of 10, 49.5 and 0.5.
Is it somehow overwriting those values? I tried grepping for 49.5 in src code but nothing came up.
This is my code (based on your example):

import las_reader
print(las_reader.__version__)
import datetime
import numpy
import os
#import matplotlib.pyplot as plt

depths = numpy.arange(10, 50, 0.5)
synth = numpy.log10(depths) * 10 + numpy.random.random(len(depths))
synth[15:25] = numpy.nan   # Add some null values in the middle

l = las_reader.LASFile()
l.well["DATE"].value = str(datetime.datetime.today())
l.well["STRT"].value = "0.25"
l.well["STOP"].value = "5000.25"
l.well["STEP"].value = "1"
l.well["NULL"].value = "-9999"
l.well["FLD"].value  = "MY WELL"
l.well["COMP"].value = "MY COMPANY"
print(l.well)
#HeaderItem: mnemonic, unit, value, descr
l.other = "Example of how to create a LAS file from scratch using las_reader"

l.add_curve("DEPT", depths, unit="m")
l.add_curve("SYNTH", synth, descr="Synthetic data")

fn = "scratch_example_v2.las"
if os.path.exists(fn):  # Remove file if it already exists
    os.remove(fn)
with open(fn, mode="w") as f: # Write LAS file to disk
    l.write(f,2)

**Comment by kinverarity1** [comment]
Ah yes the STRT, STOP and STEP values are being calculated automatically and overwritten from the first curve (i.e. the ``index`` attribute) in the ``write`` method:

```python
        self.well["STRT"].value = self.index[0]
        self.well["STOP"].value = self.index[-1]
        self.well["STEP"].value = numpy.gradient(self.index)[0]
```

(lines 257-9)

If you change the DEPT curve itself then they should update when you write the file out... I think that should be the desired behaviour (?)

**Comment by diverdude** [comment]
Ahhh yes ok. Sorry - my misunderstanding. 
Yes that is definitly the desired behaviour :)

**Comment by diverdude** [comment]
However, maybe it should be possible to override the automatic calculation?
Lets say that maybe there is an error in the depth measurement, such that there first difference: 
numpy.gradient(self.index)[0]
is different from the actual difference.

**Comment by kinverarity1** [comment]
Yep that's a very good point. Although most other software will get upset and/or confused if the actual step size in the data itself is not constant. I've just put a commit in that gives an override keyword argument for all three.
