### ISSUE TITLE
PyPI 0.5.2 version AttributeError: 'Curve' object has no attribute 'name'

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [kinverarity1/las-reader#39]
Looks like Curve 'name' attribute disappeared in 0.5 version, but still used in the function ``get_curve_name``

```
Mac$ pip3 install las_reader --upgrade
Collecting las-reader
  Using cached las_reader-0.5.2-py2.py3-none-any.whl
Requirement already up-to-date: numpy in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from las-reader)
Requirement already up-to-date: namedlist in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from las-reader)
Installing collected packages: las-reader
  Found existing installation: las-reader 0.5
    Uninstalling las-reader-0.5:
      Successfully uninstalled las-reader-0.5
Successfully installed las-reader-0.5.2
Mac$ python3
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from las_reader import read
>>> f = 'xxx.las'
>>> l = read(f, autodetect_encoding=True)
>>> for i in l:
...     print(i)
...     c = l.get_curve_name(i)
... 
DEPT
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/las_reader/las.py", line 352, in get_curve_name
    if curve.name == curve_name:
AttributeError: 'Curve' object has no attribute 'name'
>>> 
```

**Comment by diverdude** [comment]
Yep, I am getting that same error.
I made a pull request for that one just now - seems the author made a
slight typo...writing name instead of mnemonic.


On Mon, Aug 3, 2015 at 11:44 PM, Velizar VESSELINOV <
notifications@github.com> wrote:

> Mac$ pip3 install las_reader --upgrade
> Collecting las-reader
>   Using cached las_reader-0.5.2-py2.py3-none-any.whl
> Requirement already up-to-date: numpy in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from las-reader)
> Requirement already up-to-date: namedlist in /Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages (from las-reader)
> Installing collected packages: las-reader
>   Found existing installation: las-reader 0.5
>     Uninstalling las-reader-0.5:
>       Successfully uninstalled las-reader-0.5
> Successfully installed las-reader-0.5.2
> Mac$ python3
> Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03)
> [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from las_reader import read
> >>> f = 'xxx.las'
> >>> l = read(f, autodetect_encoding=True)
> >>> for i in list(l.keys()):
> ...     print(i)
> ...     c = l.get_curve_name(i)
> ...
> DEPT
> Traceback (most recent call last):
>   File "<stdin>", line 3, in <module>
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/las_reader/las.py", line 352, in get_curve_name
>     if curve.name == curve_name:
> AttributeError: 'Curve' object has no attribute 'name'
> >>>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kinverarity1/las-reader/issues/39>.
>



-- 
Med venlig hilsen
Bjørn Skovlund Dissing

**Comment by VelizarVESSELINOV** [comment]
I changed my way to loop the curves to avoid using ``get_curve_name`` function

```
for c in l.curves:
        v = c.data
        n = c.mnemonic
        u = c.unit
```

**Comment by kinverarity1** [comment]
I've changed the API so that the method is now ``get_curve``. Example is still to be written, but Velizar's method above is a good one that won't change in the future.
